/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.avans.ivh5.client.presentation;

import edu.avans.ivh5.shared.models.Client;
import java.awt.Frame;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Bart Donders
 */
public class ClientGUI extends javax.swing.JFrame {

    /**
     * Creates new form ClientGUI
     */
    public ClientGUI() {
        initComponents();
        this.setExtendedState(this.getExtendedState() | JFrame.MAXIMIZED_BOTH);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        javax.swing.JTable clientsTable = new javax.swing.JTable();
        searchClientButton = new javax.swing.JButton();
        searchClientTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        addClientButton = new javax.swing.JButton();
        deleteClientButton = new javax.swing.JButton();
        clientPanel = new javax.swing.JPanel();
        clientFirstNameLabel = new javax.swing.JLabel();
        clientLastNameLabel = new javax.swing.JLabel();
        clientBSNLabel = new javax.swing.JLabel();
        clientAddressLabel = new javax.swing.JLabel();
        clientPostCodeLabel = new javax.swing.JLabel();
        clientCityLabel = new javax.swing.JLabel();
        clientTelLabel = new javax.swing.JLabel();
        clientEmailLabel = new javax.swing.JLabel();
        clientPolisLabel = new javax.swing.JLabel();
        clientFirstNameTextField = new javax.swing.JTextField();
        clientLastNameTextField = new javax.swing.JTextField();
        clientBSNTextField = new javax.swing.JTextField();
        clientAddressTextField = new javax.swing.JTextField();
        clientPostCodeTextField = new javax.swing.JTextField();
        clientCityTextField = new javax.swing.JTextField();
        clientTelTextField = new javax.swing.JTextField();
        clientEmailTextField = new javax.swing.JTextField();
        clientIncassoCombobox = new javax.swing.JComboBox();
        addInsuranceContractButton = new javax.swing.JButton();
        saveClientButton = new javax.swing.JButton();
        clientIncassoLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        treatmentsTable = new javax.swing.JTable();
        getInvoiceButton = new javax.swing.JButton();
        clientIBANTextField = new javax.swing.JTextField();
        clientEmailLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Clientbeheer");
        setMinimumSize(null);
        setName("Clientbeheer"); // NOI18N

        clientsTable.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        clientsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Voornaam ", "Achternaam", "BSN"
            }
        ));
        clientsTable.setMaximumSize(null);
        clientsTable.setMinimumSize(null);
        jScrollPane1.setViewportView(clientsTable);

        searchClientButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        searchClientButton.setText("Zoeken");

        searchClientTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        searchClientTextField.setText("Zoekterm...");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 153, 255));
        jLabel1.setText("Clientbeheer");

        addClientButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        addClientButton.setText("Client toevoegen");
        addClientButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addClientButtonActionPerformed(evt);
            }
        });

        deleteClientButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        deleteClientButton.setText("Client verwijderen");
        deleteClientButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteClientButtonActionPerformed(evt);
            }
        });

        clientPanel.setVisible(false);
        clientPanel.setBackground(new java.awt.Color(255, 255, 255));

        clientFirstNameLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        clientFirstNameLabel.setText("Voornaam:");

        clientLastNameLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        clientLastNameLabel.setText("Achternaam:");

        clientBSNLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        clientBSNLabel.setText("BSN:");

        clientAddressLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        clientAddressLabel.setText("Straat + huisnr:");

        clientPostCodeLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        clientPostCodeLabel.setText("Postcode:");

        clientCityLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        clientCityLabel.setText("Plaats:");

        clientTelLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        clientTelLabel.setText("Telefoonnummer:");

        clientEmailLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        clientEmailLabel.setText("IBAN:");

        clientPolisLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        clientPolisLabel.setText("Polis:");

        clientFirstNameTextField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        clientFirstNameTextField.setToolTipText("Voornaam");
        clientFirstNameTextField.setName(""); // NOI18N
        clientFirstNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientFirstNameTextFieldActionPerformed(evt);
            }
        });

        clientLastNameTextField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        clientLastNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientLastNameTextFieldActionPerformed(evt);
            }
        });

        clientBSNTextField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        clientBSNTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientBSNTextFieldActionPerformed(evt);
            }
        });

        clientAddressTextField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        clientAddressTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientAddressTextFieldActionPerformed(evt);
            }
        });

        clientPostCodeTextField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        clientPostCodeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientPostCodeTextFieldActionPerformed(evt);
            }
        });

        clientCityTextField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        clientCityTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientCityTextFieldActionPerformed(evt);
            }
        });

        clientTelTextField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        clientTelTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientTelTextFieldActionPerformed(evt);
            }
        });

        clientEmailTextField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        clientEmailTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientEmailTextFieldActionPerformed(evt);
            }
        });

        clientIncassoCombobox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        clientIncassoCombobox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Nee", "Ja" }));

        addInsuranceContractButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        addInsuranceContractButton.setText("Voeg polis toe");

        saveClientButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        saveClientButton.setText("Opslaan");
        saveClientButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveClientButtonActionPerformed(evt);
            }
        });

        clientIncassoLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        clientIncassoLabel1.setText("Incasso:");

        treatmentsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Behandelcode", "Einddatum behandeling"
            }
        ));
        jScrollPane2.setViewportView(treatmentsTable);

        getInvoiceButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getInvoiceButton.setText("Toon factuur");
        getInvoiceButton.setActionCommand("");
        getInvoiceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getInvoiceButtonActionPerformed(evt);
            }
        });

        clientIBANTextField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        clientIBANTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientIBANTextFieldActionPerformed(evt);
            }
        });

        clientEmailLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        clientEmailLabel1.setText("Email:");

        javax.swing.GroupLayout clientPanelLayout = new javax.swing.GroupLayout(clientPanel);
        clientPanel.setLayout(clientPanelLayout);
        clientPanelLayout.setHorizontalGroup(
            clientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clientPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(clientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(clientPanelLayout.createSequentialGroup()
                        .addGroup(clientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(clientPanelLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(getInvoiceButton, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(clientPanelLayout.createSequentialGroup()
                                .addGroup(clientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(clientPanelLayout.createSequentialGroup()
                                        .addGroup(clientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(clientFirstNameLabel)
                                            .addComponent(clientLastNameLabel)
                                            .addComponent(clientBSNLabel)
                                            .addComponent(clientAddressLabel)
                                            .addComponent(clientPostCodeLabel)
                                            .addComponent(clientCityLabel)
                                            .addComponent(clientTelLabel))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(clientPanelLayout.createSequentialGroup()
                                        .addGroup(clientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(clientIncassoLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(clientPanelLayout.createSequentialGroup()
                                                .addGroup(clientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(clientPolisLabel)
                                                    .addComponent(clientEmailLabel1))
                                                .addGap(0, 86, Short.MAX_VALUE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGap(29, 29, 29)
                                .addGroup(clientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(clientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(clientEmailTextField)
                                        .addComponent(clientCityTextField)
                                        .addComponent(clientPostCodeTextField)
                                        .addComponent(clientAddressTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
                                        .addComponent(clientBSNTextField)
                                        .addComponent(clientLastNameTextField)
                                        .addComponent(clientFirstNameTextField))
                                    .addComponent(clientTelTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(clientIBANTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(clientIncassoCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(addInsuranceContractButton, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(saveClientButton, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 14, Short.MAX_VALUE)))
                        .addGap(13, 13, 13))
                    .addGroup(clientPanelLayout.createSequentialGroup()
                        .addComponent(clientEmailLabel)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        clientPanelLayout.setVerticalGroup(
            clientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clientPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(clientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clientFirstNameLabel)
                    .addComponent(clientFirstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(clientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clientLastNameLabel)
                    .addComponent(clientLastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(clientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clientBSNLabel)
                    .addComponent(clientBSNTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(clientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clientAddressLabel)
                    .addComponent(clientAddressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(clientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clientPostCodeLabel)
                    .addComponent(clientPostCodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(clientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clientCityLabel)
                    .addComponent(clientCityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(clientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clientTelLabel)
                    .addComponent(clientTelTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(clientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clientEmailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clientEmailLabel1))
                .addGap(7, 7, 7)
                .addGroup(clientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clientEmailLabel)
                    .addComponent(clientIBANTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(clientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clientIncassoCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clientIncassoLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(clientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addInsuranceContractButton)
                    .addComponent(clientPolisLabel))
                .addGap(18, 18, 18)
                .addComponent(saveClientButton)
                .addGap(20, 20, 20)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(getInvoiceButton)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        clientFirstNameTextField.getAccessibleContext().setAccessibleName("");
        clientFirstNameTextField.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addClientButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(deleteClientButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(searchClientTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(searchClientButton, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 261, Short.MAX_VALUE)
                .addComponent(clientPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchClientTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchClientButton, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addClientButton)
                    .addComponent(deleteClientButton))
                .addGap(40, 40, 40))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(clientPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addClientButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addClientButtonActionPerformed
        clientPanel.setVisible(true);
    }//GEN-LAST:event_addClientButtonActionPerformed

    private void clientIBANTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientIBANTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clientIBANTextFieldActionPerformed

    private void getInvoiceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getInvoiceButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_getInvoiceButtonActionPerformed

    private void clientEmailTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientEmailTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clientEmailTextFieldActionPerformed

    private void clientTelTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientTelTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clientTelTextFieldActionPerformed

    private void clientCityTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientCityTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clientCityTextFieldActionPerformed

    private void clientPostCodeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientPostCodeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clientPostCodeTextFieldActionPerformed

    private void clientAddressTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientAddressTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clientAddressTextFieldActionPerformed

    private void clientBSNTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientBSNTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clientBSNTextFieldActionPerformed

    private void clientLastNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientLastNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clientLastNameTextFieldActionPerformed

    private void clientFirstNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientFirstNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clientFirstNameTextFieldActionPerformed

    private void saveClientButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveClientButtonActionPerformed
        String BSN = clientBSNTextField.getText();
        String name = clientLastNameTextField.getText();
        String firstName = clientFirstNameTextField.getText();
        String city = clientCityTextField.getText();
        String postcode = clientPostCodeTextField.getText();
        String address = clientAddressTextField.getText();
        String IBAN = clientIBANTextField.getText();
        boolean incasso;
        if (clientIncassoCombobox.getSelectedItem().toString().equals("Nee")) {
            incasso = false;
        } else {
            incasso = true;
        }
        String email = clientEmailTextField.getText();
        String tel = clientTelTextField.getText();
        Client client = new Client(BSN, name, firstName, city, postcode, address, IBAN, incasso, email, tel);
    }//GEN-LAST:event_saveClientButtonActionPerformed

    private void deleteClientButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteClientButtonActionPerformed
     Object[] options = {"Ja", "Nee"};
        JOptionPane.showOptionDialog(null, "Weet u zeker dat u deze client wilt verwijderen?", "Verwijderen", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[1]);
    }//GEN-LAST:event_deleteClientButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addClientButton;
    private javax.swing.JButton addInsuranceContractButton;
    private javax.swing.JLabel clientAddressLabel;
    private javax.swing.JTextField clientAddressTextField;
    private javax.swing.JLabel clientBSNLabel;
    private javax.swing.JTextField clientBSNTextField;
    private javax.swing.JLabel clientCityLabel;
    private javax.swing.JTextField clientCityTextField;
    private javax.swing.JLabel clientEmailLabel;
    private javax.swing.JLabel clientEmailLabel1;
    private javax.swing.JTextField clientEmailTextField;
    private javax.swing.JLabel clientFirstNameLabel;
    private javax.swing.JTextField clientFirstNameTextField;
    private javax.swing.JTextField clientIBANTextField;
    private javax.swing.JComboBox clientIncassoCombobox;
    private javax.swing.JLabel clientIncassoLabel1;
    private javax.swing.JLabel clientLastNameLabel;
    private javax.swing.JTextField clientLastNameTextField;
    private javax.swing.JPanel clientPanel;
    private javax.swing.JLabel clientPolisLabel;
    private javax.swing.JLabel clientPostCodeLabel;
    private javax.swing.JTextField clientPostCodeTextField;
    private javax.swing.JLabel clientTelLabel;
    private javax.swing.JTextField clientTelTextField;
    private javax.swing.JButton deleteClientButton;
    private javax.swing.JButton getInvoiceButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton saveClientButton;
    private javax.swing.JButton searchClientButton;
    private javax.swing.JTextField searchClientTextField;
    private javax.swing.JTable treatmentsTable;
    // End of variables declaration//GEN-END:variables
}
